# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- rvm install ruby-2.3.1 && rvm use 2.3.1 
- gem install xcpretty
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- pod lib lint
script:
- set -o pipefail && xcodebuild test -workspace Example/CPCollectionViewWheelLayoutSwift.xcworkspace -scheme CPCollectionViewWheelLayoutSwift-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty