# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- rvm install ruby-2.3.1 && rvm use 2.3.1 
- gem install xcpretty
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
after_install:
- pod lib lint
script:
- set -o pipefail
- xctool -project CPCollectionViewWheelLayoutSwift.xcodeproj -scheme CPCollectionViewWheelLayoutSwift -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- xctool test -workspace Example/CPCollectionViewWheelLayoutSwift.xcworkspace -scheme CPCollectionViewWheelLayoutSwift_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty

notifications:
  email: false
after_success:
- bash <(curl -s https://codecov.io/bash)